'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ni.gob.bcn.servicios
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Tipo_Cambio_BCNSoap", [Namespace]:="http://servicios.bcn.gob.ni/")>  _
    Partial Public Class Tipo_Cambio_BCN
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RecuperaTC_DiaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecuperaTC_MesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApp1.My.MySettings.Default.WindowsApp1_ni_gob_bcn_servicios_Tipo_Cambio_BCN
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RecuperaTC_DiaCompleted As RecuperaTC_DiaCompletedEventHandler
        
        '''<remarks/>
        Public Event RecuperaTC_MesCompleted As RecuperaTC_MesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.bcn.gob.ni/RecuperaTC_Dia", RequestNamespace:="http://servicios.bcn.gob.ni/", ResponseNamespace:="http://servicios.bcn.gob.ni/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperaTC_Dia(ByVal Ano As Integer, ByVal Mes As Integer, ByVal Dia As Integer) As Double
            Dim results() As Object = Me.Invoke("RecuperaTC_Dia", New Object() {Ano, Mes, Dia})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperaTC_DiaAsync(ByVal Ano As Integer, ByVal Mes As Integer, ByVal Dia As Integer)
            Me.RecuperaTC_DiaAsync(Ano, Mes, Dia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperaTC_DiaAsync(ByVal Ano As Integer, ByVal Mes As Integer, ByVal Dia As Integer, ByVal userState As Object)
            If (Me.RecuperaTC_DiaOperationCompleted Is Nothing) Then
                Me.RecuperaTC_DiaOperationCompleted = AddressOf Me.OnRecuperaTC_DiaOperationCompleted
            End If
            Me.InvokeAsync("RecuperaTC_Dia", New Object() {Ano, Mes, Dia}, Me.RecuperaTC_DiaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperaTC_DiaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperaTC_DiaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperaTC_DiaCompleted(Me, New RecuperaTC_DiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.bcn.gob.ni/RecuperaTC_Mes", RequestNamespace:="http://servicios.bcn.gob.ni/", ResponseNamespace:="http://servicios.bcn.gob.ni/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperaTC_Mes(ByVal Ano As Integer, ByVal Mes As Integer) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("RecuperaTC_Mes", New Object() {Ano, Mes})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperaTC_MesAsync(ByVal Ano As Integer, ByVal Mes As Integer)
            Me.RecuperaTC_MesAsync(Ano, Mes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperaTC_MesAsync(ByVal Ano As Integer, ByVal Mes As Integer, ByVal userState As Object)
            If (Me.RecuperaTC_MesOperationCompleted Is Nothing) Then
                Me.RecuperaTC_MesOperationCompleted = AddressOf Me.OnRecuperaTC_MesOperationCompleted
            End If
            Me.InvokeAsync("RecuperaTC_Mes", New Object() {Ano, Mes}, Me.RecuperaTC_MesOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperaTC_MesOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperaTC_MesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperaTC_MesCompleted(Me, New RecuperaTC_MesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RecuperaTC_DiaCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperaTC_DiaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperaTC_DiaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RecuperaTC_MesCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperaTC_MesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperaTC_MesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
End Namespace
